<h1>Problem 1: Factorials using numpy</h1>
<li><b>prod</b> A numpy function that returns the product of all elements in an array
<li><b>cumprod</b> A numpy function on an ndarray of size n that returns an array of size n where each element i is the product of all elements from 0 to i


In [1]:
import numpy as np
"""
Replace pass with the code that uses ndarray, prod and cumprod 
to calculate the factorial of n

The function should take an integer as an argument and return an integer

"""
def factorial(n):
    m = np.arange(n+1)
    return np.prod(m[1:])

factorial(0)

1

In [2]:
"""
Replace pass with the code that uses ndarray, prod and cumprod to 
calculate the factorials of all values from 1 to n

The function should take an integer as an argument and return an ndarray
of size n 

"""

def all_factorials(n):
    m = np.arange(n+1)
    if n==0:
        return np.array([1])
    
    return(np.cumprod(m[1:]))

all_factorials(2)

array([1, 2])

In [3]:
"""
Replace pass with the code that use ndarray, np.prod, and np.where 
to calculate the product of elements in array that are divisible by i

The function should take an array and an integer(i) as arguments and return an integer

"""
def func(array,i):
    m = np.where(array%i==0, 1, 0)
    return np.prod(array[m>0])
    
        
func(np.array([3,6,7]),3)

18

<h1>Problem 2: Percent changes</h1>
Write a function that constructs an ndarray from data in a file and 
returns a 1-period percent change on an ndarray after removing any nan values. Your function must make use of the following functions:
<li>np.genfromtxt: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.genfromtxt.html
<li>np.diff: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.diff.html
<li>np.isnan: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.isnan.html

<p>Test your function out using the attached apple.csv file. Your function can assume that the file structure is (date,price)

<p>Note that percent change is defined as (p(t)-p(t-1))/p(t-1)

<b>Example:</b><br>
If the data array is: np.array([1,2,np.NaN,4,8,np.NAN])
<br>
The output array should be<br>
array([ 1.,  1.,  1.])


In [4]:
import math
def get_pct_changes(file_name):
    price = np.genfromtxt(file_name, delimiter=',')
    price=price[:,1]
    price2 = np.roll(price,1)
    returns=np.diff(price)/price2[1:]
    mask = np.isnan(returns)
    return returns[mask==False]

get_pct_changes('apple.csv')

array([-0.05217305, -0.07339571,  0.02475207, ..., -0.00977899,
       -0.00882215,  0.01720356])

<h1>Problem 3: Pandas Grouping</h1>
Write a program that reads timeseries pricing data from a file into a pandas dataframe and then groups the data as follows:
<li>Adds a column, 'one-day percent change' to the file 
<li>Write a function that groups the data into four categories:
<ul>
<li>"High+" if the percent change is greater than 2.5%
<li>"Low+" if the percent change is positive and less than or equal to 2.5% 
<li>"Low-" if the percent change is negative but greater than or equal to -2.5%
<li>"High-" if the percent change is less than -2.5%
</ul>
<li>Report the size and the mean of each groups in dataframe



In [5]:
datafile = "apple.csv"
import pandas as pd
df = pd.read_csv('apple.csv',na_values='null')
df

Date   Adj Close
0     1980-12-12    0.421597
1     1980-12-15    0.399601
2     1980-12-16    0.370272
3     1980-12-17    0.379437
4     1980-12-18    0.390436
...          ...         ...
9273  2017-09-20  156.070007
9274  2017-09-21  153.389999
9275  2017-09-22  151.889999
9276  2017-09-25  150.550003
9277  2017-09-26  153.139999

[9278 rows x 2 columns]

In [6]:
#Adds column 'one-day percent change'
df.set_index(df['Date'], inplace=True, drop=True)
df.index = pd.to_datetime(df.index)
df['one-day percent change'] = df['Adj Close'].pct_change()



In [12]:
def GroupColFunc(df, ind, col='one-day percent change'):
   
    if df[col].loc[ind]>2.5/100:
        #print(col,ind)
        return 'High+'

    elif 0<df[col].loc[ind]<=2.5/100:
        return 'Low+'
    elif -2.5/100<=df[col].loc[ind]<0:
        return 'Low-'
    elif df[col].loc[ind]==np.nan or df[col].loc[ind]==0:
        return
    else:
        return'High-'



In [8]:
#report size and mean
grouped = df.groupby(lambda x: GroupColFunc(df, x))
print(f"GROUPS SIZE: {grouped.size()}")
print()
print(f"GROUPS MEAN: {grouped.mean()}")


GROUPS SIZE: Date
High+    1391
High-    1577
Low+     3170
Low-     3140
dtype: int64

GROUPS MEAN:        Adj Close  one-day percent change
Date                                    
High+   8.652295                0.045705
High-   6.724694               -0.033950
Low+   26.292799                0.011020
Low-   24.183470               -0.011171


Write a program that can choose decade and report the size and the mean of each group in dataframe
<li>Adds a column 'Decade' to the file (use first three numbers to be value of the decade ex. value for 1980-1989 is '198')  
<li>Write a function that have data from a file with decade column and decade as input
<li>Call function that you create in the first part to group the data
<li>Return dataframe of mean and size for each group of that decade

In [9]:
#adds column 'Decade'
for i in df.index:
    year = str(i.year)
    df.loc[i,'Decade'] = year[:-1]

df.head()

Date  Adj Close  one-day percent change Decade
Date                                                            
1980-12-12  1980-12-12   0.421597                     NaN    198
1980-12-15  1980-12-15   0.399601               -0.052173    198
1980-12-16  1980-12-16   0.370272               -0.073396    198
1980-12-17  1980-12-17   0.379437                0.024752    198
1980-12-18  1980-12-18   0.390436                0.028988    198

In [10]:

def report_decade(df,decade):
    #Your code goes here
    new_df = df[df['Decade']==str(decade)]
    #print(new_df.tail())
    #new_df.set_index(range(len(new_df)), inplace=True)
    #print(new_df)
    grouped = new_df.groupby(lambda x: GroupColFunc(new_df, x))
    my_summary = grouped.mean()
    my_summary['Size'] = grouped.size()
    return my_summary

In [13]:
#Test
report_decade(df,'198')

Adj Close  one-day percent change  Size
Date                                          
High+   0.607085                0.046111   404
High-   0.582032               -0.045644   351
Low+    0.725060                0.012576   657
Low-    0.687610               -0.012965   683