<h1>Problem 1: Factorials using numpy</h1>
<li><b>prod</b> A numpy function that returns the product of all elements in an array
<li><b>cumprod</b> A numpy function on an ndarray of size n that returns an array of size n where each element i is the product of all elements from 0 to i


In [16]:
import numpy as np

In [17]:
"""
Replace pass with the code that uses ndarray, prod and cumprod 
to calculate the factorial of n

The function should take an integer as an argument and return an integer

"""
def factorial(n):
    #pass
    if n==0:
        return 1
    
    return np.prod(np.arange(1,n+1))
    





In [18]:
"""
Replace pass with the code that uses ndarray, prod and cumprod to 
calculate the factorials of all values from 1 to n

The function should take an integer as an argument and return an ndarray
of size n 

"""

def all_factorials(n):
    #pass
    
    
    if n==0:
        return np.array([1])
    
    
    return np.cumprod(np.arange(1,n+1))
    
    
    

In [19]:
"""
Replace pass with the code that use ndarray, np.prod, and np.where 
to calculate the product of elements in array that are divisible by i

The function should take an array and an integer(i) as arguments and return an integer

"""
def func(array,i):
    #pass
    if i==0:
        return 0
    
    return np.where( np.array(array)%i == 0, True, False).sum()
        


<h1>Problem 2: Percent changes</h1>
Write a function that constructs an ndarray from data in a file and 
returns a 1-period percent change on an ndarray after removing any nan values. Your function must make use of the following functions:
<li>np.genfromtxt: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.genfromtxt.html
<li>np.diff: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.diff.html
<li>np.isnan: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.isnan.html

<p>Test your function out using the attached apple.csv file. Your function can assume that the file structure is (date,price)

<p>Note that percent change is defined as (p(t)-p(t-1))/p(t-1)

<b>Example:</b><br>
If the data array is: np.array([1,2,np.NaN,4,8,np.NAN])
<br>
The output array should be<br>
array([ 1.,  1.,  1.])


In [20]:
#just a test
arr=np.array([1,2,np.NaN,4,8,np.NAN])

#select all of the elements that are not nan
arr=arr[~np.isnan(arr)]


np.diff(arr)/arr[:-1] 


array([1., 1., 1.])

In [21]:
def get_pct_changes(file_name):
    #pass
    data= np.genfromtxt(file_name, delimiter=',', skip_header=1)
    prices=data[:, 1]
    prices=prices[~np.isnan(prices)]
    return np.diff(prices)/prices[:-1] 
    

In [22]:
get_pct_changes('apple.csv')

array([-0.05217305, -0.07339571,  0.02475207, ..., -0.00977899,
       -0.00882215,  0.01720356])

<h1>Problem 3: Pandas Grouping</h1>
Write a program that reads timeseries pricing data from a file into a pandas dataframe and then groups the data as follows:
<li>Adds a column, 'one-day percent change' to the file 
<li>Write a function that groups the data into four categories:
<ul>
<li>"High+" if the percent change is greater than 2.5%
<li>"Low+" if the percent change is positive and less than or equal to 2.5% 
<li>"Low-" if the percent change is negative but greater than or equal to -2.5%
<li>"High-" if the percent change is less than -2.5%
</ul>
<li>Report the size and the mean of each groups in dataframe



In [23]:
datafile = "apple.csv"
import pandas as pd
df = pd.read_csv('apple.csv',na_values='null')
df['Date']=pd.to_datetime(df['Date']) #we change the type to datetime

In [24]:
#Adds column 'one-day percent change'
df['one-day percent change']=df['Adj Close'].pct_change()
df

Date   Adj Close  one-day percent change
0    1980-12-12    0.421597                     NaN
1    1980-12-15    0.399601               -0.052173
2    1980-12-16    0.370272               -0.073396
3    1980-12-17    0.379437                0.024752
4    1980-12-18    0.390436                0.028988
...         ...         ...                     ...
9273 2017-09-20  156.070007               -0.016758
9274 2017-09-21  153.389999               -0.017172
9275 2017-09-22  151.889999               -0.009779
9276 2017-09-25  150.550003               -0.008822
9277 2017-09-26  153.139999                0.017204

[9278 rows x 3 columns]

In [25]:
def GroupColFunc(df, ind, col):
    if df[col].loc[ind]>0.025:
        return 'High+'
    elif df[col].loc[ind]>=0 and df[col].loc[ind]<=0.025:
        return 'Low+'
    elif df[col].loc[ind]<0 and df[col].loc[ind]>=-0.025:
        return 'Low-'
    else:
        return 'High-'


In [26]:
grouped = df.groupby(lambda x: GroupColFunc(df=df, ind=x, col='one-day percent change'))


In [27]:
#report size and mean
print('groups size:')
print(grouped.size())
print('\n')
print('groups mean:')
print(grouped.mean())

groups size:
High+    1391
High-    1211
Low+     3536
Low-     3140
dtype: int64


groups mean:
       Adj Close  one-day percent change
High+   8.652295                0.045705
High-   8.282568               -0.044220
Low+   23.738642                0.009879
Low-   24.183470               -0.011171


Write a program that can choose decade and report the size and the mean of each group in dataframe
<li>Adds a column 'Decade' to the file (use first three numbers to be value of the decade ex. value for 1980-1989 is '198')  
<li>Write a function that have data from a file with decade column and decade as input
<li>Call function that you create in the first part to group the data
<li>Return dataframe of mean and size for each group of that decade

In [28]:
#adds column 'Decade'
df['Decade']=df['Date'].apply(lambda x: str(x.year)[:3])
df

Date   Adj Close  one-day percent change Decade
0    1980-12-12    0.421597                     NaN    198
1    1980-12-15    0.399601               -0.052173    198
2    1980-12-16    0.370272               -0.073396    198
3    1980-12-17    0.379437                0.024752    198
4    1980-12-18    0.390436                0.028988    198
...         ...         ...                     ...    ...
9273 2017-09-20  156.070007               -0.016758    201
9274 2017-09-21  153.389999               -0.017172    201
9275 2017-09-22  151.889999               -0.009779    201
9276 2017-09-25  150.550003               -0.008822    201
9277 2017-09-26  153.139999                0.017204    201

[9278 rows x 4 columns]

In [29]:
def report_decade(df,decade):
    #Your code goes here
    df_decade=df[df['Decade']==decade]
    
    grouped = df_decade.groupby(lambda x: GroupColFunc(df=df_decade, ind=x, col='one-day percent change'))
    
    size=pd.Series(grouped.size(), name='Size') #Add name to the series
    
    result=pd.concat([size, grouped.mean()] , axis=1) #concat the series to make one dataframe
    
    return result
    

In [30]:
#Test
report_decade(df,'198')

Size  Adj Close  one-day percent change
High+   404   0.607085                0.046111
High-   351   0.582032               -0.045644
Low+    850   0.701085                0.009720
Low-    683   0.687610               -0.012965