<h2>Three Types of Indexing Supported </h2>

In [1]:
import numpy as np

a = np.arange(1,20,3) 
b = np.arange(15)
ax = np.array(b.reshape(3,5))
print("a = ",a,"\n")
print ("ax = ","\n\n", ax)

a =  [ 1  4  7 10 13 16 19] 

ax =  

 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


<h3>field access (1-d array)</h3>

In [2]:
a[[1,4]] 

array([ 4, 13])

<h3>field access (multi-dim array)</h3>

<h3>basic slicing (1-d array)</h3>

In [3]:
a[2:7:2]

array([ 7, 13, 19])

<h3>basic slicing (multi-dim array)</h3>

In [4]:
ax[1:3,2:4]

array([[ 7,  8],
       [12, 13]])

<h3>advanced indexing using arrays</h3>

In [5]:
ay = np.array([[2,4],[1,3]])
a[ay]

array([[ 7, 13],
       [ 4, 10]])

In [6]:
az = np.array([[0,2],[1,0]])
print(ax[az].shape)
print(az.shape)

(2, 2, 5)
(2, 2)


In [30]:
i = np.array([1,0])
j = np.array([1,2])
k = np.array([[1,0],[0,2]])
# ax[i] 
# ax[j]
ax[i,j]
# ax[0:1,:]
# ax[[1],[0,2]]
ax[k]


array([[[ 5,  6,  7,  8,  9],
        [ 0,  1,  2,  3,  4]],

       [[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14]]])

In [8]:
# ax[i,j]

<h3>getting the corners of the array as a 2-d array</h3>

In [9]:
rows2 = np.array([[0,0],[2,2]])
cols2 = np.array([[0,4],[0,4]])
ax[rows2,cols2]

array([[ 0,  4],
       [10, 14]])

<h3>getting corners using slicing</h3>

In [10]:
ax[0:3:2,0:5:4]

array([[ 0,  4],
       [10, 14]])

<h3>Can combine slice for row and advance indexing for column</h3>

In [11]:
ax[1:3,[2,3,4]] 

array([[ 7,  8,  9],
       [12, 13, 14]])

In [12]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row, col]

array([ 2,  5, 11])

In [14]:
row[:, np.newaxis]

array([[0],
       [1],
       [2]])

In [15]:
col[:, np.newaxis]

array([[2],
       [1],
       [3]])

In [16]:
X[row[:, np.newaxis], col]


array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

In [17]:
row2 = np.array([0,2,1])
X[row2[:, np.newaxis], col]

array([[ 2,  1,  3],
       [10,  9, 11],
       [ 6,  5,  7]])

In [18]:
row[:, np.newaxis]*col

array([[0, 0, 0],
       [2, 1, 3],
       [4, 2, 6]])

In [19]:
X[row[:, np.newaxis], col[:, np.newaxis]]

array([[ 2],
       [ 5],
       [11]])